# Spring Boot
logging.config=classpath:logback-nais.xml
spring.jmx.enabled=false
spring.main.banner_mode=off
server.shutdown=graceful

camel.main.name=dokopp
camel.main.shutdown-timeout=30
camel.main.jmx-enabled=false
camel.mdc.enabled=true

# Actuator
management.endpoints.web.exposure.include=health, prometheus
