kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: DOKOPP_CHANNEL_NAME
      value: {{ DOKOPP_CHANNEL_NAME }}
    - name: DOKOPP_QOPP001_OPPRETT_OPPGAVE_QUEUENAME
      value: {{ DOKOPP_QOPP001_OPPRETT_OPPGAVE_QUEUENAME }}
    - name: DOKOPP_QOPP001_FUNKSJONELL_FEIL_QUEUENAME
      value: {{ DOKOPP_QOPP001_FUNKSJONELL_FEIL_QUEUENAME }}
    - name: DOKOPP_PROXY_HOST
      value: {{ DOKOPP_PROXY_HOST }}
    - name: DOKOPP_PROXY_PORT
      value: "{{DOKOPP_PROXY_PORT}}"
    - name: DOKOPP_ENDPOINTS_SAF_SCOPE
      value: {{ DOKOPP_ENDPOINTS_SAF_SCOPE }}
    - name: DOKOPP_ENDPOINTS_SAF_URL
      value: {{ DOKOPP_ENDPOINTS_SAF_URL }}
    - name: DOKOPP_ENDPOINTS_PDL
      value: {{ DOKOPP_ENDPOINTS_PDL }}
    - name: DOKOPP_ENDPOINTS_OPPGAVE
      value: {{ DOKOPP_ENDPOINTS_OPPGAVE }}
    - name: DOKOPP_ENDPOINTS_STS
      value: {{ DOKOPP_ENDPOINTS_STS }}
    - name: AZURE_APP_TOKEN_URL
      value: {{ AZURE_APP_TOKEN_URL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKOPP }}
        mountPath: /var/run/secrets/nais.io/srvdokopp
  azure:
    application:
      enabled: true
